### ISSUE TITLE
API change suggestion: Default `size` to `none` instead of `1`

### ISSUE THREAD

**Issue by uben0** [liuguangxi/suiji#1]
Currently, if `size` is `1`, the return value won't be an array, but directly the random value.

I suggest to change this behaviour when `size` is `none` and to always return an array when the `size` is an integer.

Current behaviour:
```typst
#let (rng, v) = uniform(rng, size: 1)
#repr(v)
```
```
0.18691460322588682
```

Suggested behaviour:
```typst
#let (rng, v) = uniform(rng)
#repr(v)
```
```
0.18691460322588682
```
```typst
#let (rng, v) = uniform(rng, size: 1)
#repr(v)
```
```
(0.18691460322588682,)
```
```typst
#let (rng, v) = uniform(rng, size: none)
#repr(v)
```
```
0.18691460322588682
```

**Comment by liuguangxi** [comment]
I agree with you, this would make the behavior of the return value more intuitive.
Thanks for the suggestion, and the codes of upcoming version would be updated.

**Comment by uben0** [comment]
Do you think the size could also accept `0` ? This would not make sense to use it directly, because it would return an empty array, but it might make sense in a script where the value passed as size is an variable. Because in strictly speaking, the `size` parameter is the size of an array and from what I see in the implementation, it would not need any modification except for changing the `assert(size >= 1)` to `assert(size >= 0)`.

I'm sorry if I'm annoying XD

**Comment by liuguangxi** [comment]
Hmm. It looks like NumPy Random Generator has similar behavior with size=0. In next release, the `size` parameter would be updated allowing size = 0.
